package oidc

import (
	"context"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/auth0/go-jwt-middleware/v3/jwks"
	"github.com/auth0/go-jwt-middleware/v3/validator"
	"github.com/rs/zerolog"

	"github.com/dioad/auth/jwt"
)

// isHMACAlgorithm checks if the given SignatureAlgorithm is a symmetric HMAC variant.
func isHMACAlgorithm(alg validator.SignatureAlgorithm) bool {
	return strings.HasPrefix(string(alg), "HS")
}

// TokenValidator is an alias for jwt.TokenValidator.
type TokenValidator = jwt.TokenValidator

// ValidatorOpt configures validator creation.
type ValidatorOpt func(*validatorOptions)

type validatorOptions struct {
	keyFunc      func(context.Context) (any, error)
	jwksProvider *jwks.CachingProvider
}

// WithValidatorKeyFunc sets a custom key function for validation.
func WithValidatorKeyFunc(keyFunc func(context.Context) (any, error)) ValidatorOpt {
	return func(o *validatorOptions) {
		if keyFunc != nil {
			o.keyFunc = keyFunc
		}
	}
}

// WithValidatorJWKSProvider sets a custom JWKS caching provider.
func WithValidatorJWKSProvider(provider *jwks.CachingProvider) ValidatorOpt {
	return func(o *validatorOptions) {
		if provider != nil {
			o.jwksProvider = provider
		}
	}
}

// NewValidatorFromConfig creates a TokenValidator from a ValidatorConfig.
func NewValidatorFromConfig(cfg *ValidatorConfig) (jwt.TokenValidator, error) {
	return NewValidatorFromConfigWithOptions(cfg)
}

// NewValidatorFromConfigWithOptions creates a TokenValidator from a ValidatorConfig using custom options.
func NewValidatorFromConfigWithOptions(cfg *ValidatorConfig, opts ...ValidatorOpt) (jwt.TokenValidator, error) {
	// Use a local issuer variable to avoid mutating the caller's config
	issuer := cfg.Issuer
	if issuer == "" && cfg.URL != "" {
		// For now, use the URL as issuer if not provided
		issuer = cfg.URL
	}

	algorithm := validator.SignatureAlgorithm(cfg.SignatureAlgorithm)

	options := &validatorOptions{}
	for _, opt := range opts {
		opt(options)
	}

	// Track whether HMAC mode should use flexible issuer validation
	hmacFlexibleIssuer := false

	// Static HMAC secret short-circuits JWKS discovery. Intended for local
	// development / smoke tests only.
	if cfg.HMACSecret != "" {
		secret := []byte(cfg.HMACSecret)
		// Only override keyFunc if no custom keyFunc was provided via options
		if options.keyFunc == nil {
			options.keyFunc = func(_ context.Context) (any, error) { return secret, nil }
		}
		// HMAC requires a symmetric signing algorithm (HS256/HS384/HS512).
		// Override any non-HS algorithm to prevent runtime failures.
		if algorithm == "" || !isHMACAlgorithm(algorithm) {
			algorithm = validator.HS256
		}
		// For HMAC smoke tests without an explicit issuer, accept any issuer claim.
		// If an issuer was explicitly configured, enforce it.
		if issuer == "" {
			// No issuer preference; set a dummy issuer for the validator library
			// (which requires at least one to be set), then use flexible validation.
			issuer = "local-smoke"
			hmacFlexibleIssuer = true
		}
	}

	if issuer == "" {
		return nil, fmt.Errorf("issuer or URL must be provided")
	}

	if algorithm == "" {
		algorithm = validator.RS256
	}

	if options.keyFunc == nil {
		issuerURL, err := url.Parse(issuer)
		if err != nil {
			return nil, fmt.Errorf("invalid issuer URL: %w", err)
		}
		cacheTTL := time.Duration(cfg.CacheTTL) * time.Second
		if cacheTTL <= 0 {
			cacheTTL = 5 * time.Minute
		}
		if options.jwksProvider == nil {
			var err error
			options.jwksProvider, err = jwks.NewCachingProvider(
				jwks.WithIssuerURL(issuerURL),
				jwks.WithCacheTTL(cacheTTL),
			)
			if err != nil {
				return nil, fmt.Errorf("failed to create JWKS caching provider: %w", err)
			}
		}
		options.keyFunc = options.jwksProvider.KeyFunc
	}
	if options.keyFunc == nil {
		return nil, fmt.Errorf("key function not configured")
	}

	// Build validator options.
	validatorOpts := []validator.Option{
		validator.WithKeyFunc(options.keyFunc),
		validator.WithAlgorithm(algorithm),
		validator.WithAllowedClockSkew(time.Duration(cfg.AllowedClockSkew) * time.Second),
	}
	if len(cfg.Audiences) > 0 {
		validatorOpts = append(validatorOpts, validator.WithAudiences(cfg.Audiences))
	} else if cfg.HMACSecret != "" {
		// HMAC smoke-test mode with no explicit audiences: accept the default smoke audience.
		// Tokens generated by gen_smoke_token.py include aud: "local-smoke" by default.
		validatorOpts = append(validatorOpts, validator.WithAudience("local-smoke"))
	} else {
		// Non-HMAC mode (production) requires explicit audience configuration to prevent
		// accidental deployments without audience validation, which is a critical security check.
		return nil, fmt.Errorf("audiences must be configured in non-HMAC mode")
	}

	if cfg.HMACSecret != "" && hmacFlexibleIssuer {
		// HMAC mode with no explicit issuer: accept any issuer claim by returning the token's issuer.
		// This enables flexible local smoke testing where tokens can have any iss value.
		validatorOpts = append(validatorOpts,
			validator.WithIssuersResolver(func(ctx context.Context) ([]string, error) {
				// Extract the issuer from the token (already in context by the validator)
				if iss, ok := validator.IssuerFromContext(ctx); ok && iss != "" {
					return []string{iss}, nil
				}
				// No issuer in token; return empty list which will cause validation to fail
				// (validator library requires iss claim to be present)
				return []string{}, nil
			}),
		)
	} else {
		// Normal mode or HMAC with explicit issuer: enforce the configured issuer
		validatorOpts = append(validatorOpts, validator.WithIssuer(issuer))
	}

	v, err := validator.New(validatorOpts...)
	if err != nil {
		return nil, fmt.Errorf("failed to create validator: %w", err)
	}

	var tv jwt.TokenValidator = &auth0Validator{v: v, issuer: issuer}

	if len(cfg.ClaimPredicate) > 0 {
		predicate := jwt.ParseClaimPredicates(cfg.ClaimPredicate)
		tv = &jwt.PredicateValidator{
			ParentValidator: tv,
			Predicate:       predicate,
		}
	}

	if cfg.Debug {
		tv = &validatorDebugger{TokenValidator: tv, logger: zerolog.Nop()}
	}

	return tv, nil
}

type auth0Validator struct {
	v      *validator.Validator
	issuer string
}

func (v *auth0Validator) ValidateToken(ctx context.Context, tokenString string) (any, error) {
	return v.v.ValidateToken(ctx, tokenString)
}

func (v *auth0Validator) String() string {
	return fmt.Sprintf("Auth0Validator(%s)", v.issuer)
}

type validatorDebugger struct {
	jwt.TokenValidator
	logger zerolog.Logger
}

func (v *validatorDebugger) ValidateToken(ctx context.Context, tokenString string) (any, error) {
	claims, err := v.TokenValidator.ValidateToken(ctx, tokenString)
	if err != nil {
		v.logger.Error().Err(err).Msg("Token validation failed")
	} else {
		v.logger.Debug().Msg("Token validation succeeded")
	}
	return claims, err
}

func (v *validatorDebugger) String() string {
	return fmt.Sprintf("ValidatorDebugger(%s)", v.TokenValidator.String())
}

// DebuggerOpt configures a TokenValidator debugger.
type DebuggerOpt func(*validatorDebugger)

// WithLogger sets the logger for validator debug output.
func WithLogger(logger zerolog.Logger) DebuggerOpt {
	return func(v *validatorDebugger) {
		v.logger = logger
	}
}

// NewValidatorDebugger wraps a TokenValidator with debugging output.
func NewValidatorDebugger(v jwt.TokenValidator, opts ...DebuggerOpt) jwt.TokenValidator {
	dv := &validatorDebugger{TokenValidator: v, logger: zerolog.Nop()}
	for _, opt := range opts {
		opt(dv)
	}
	return dv
}

// NewMultiValidatorFromConfig creates a MultiValidator from multiple configs.
func NewMultiValidatorFromConfig(configs []ValidatorConfig, opts ...validator.Option) (jwt.TokenValidator, error) {
	var validators []jwt.TokenValidator
	for _, cfg := range configs {
		v, err := NewValidatorFromConfig(&cfg)
		if err != nil {
			return nil, err
		}
		validators = append(validators, v)
	}
	return &jwt.MultiValidator{Validators: validators}, nil
}
